-- =============================================
-- Database Performance Optimization Script
-- Database: BHVEDPSNET
-- Purpose: Create indexes for improved query performance
-- =============================================

USE [BHVEDPSNET]
GO

PRINT 'Starting index optimization for BHVEDPSNET database...'
GO

-- =============================================
-- SECTION 1: STUDENT TABLE INDEXES
-- =============================================

-- TBL_STUDENT_INFO Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_INFO_PRN_NO' AND object_id = OBJECT_ID('TBL_STUDENT_INFO'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_INFO_PRN_NO] ON [dbo].[TBL_STUDENT_INFO] ([Chr_PRN_NO])
    INCLUDE ([Num_PK_RECORD_ID], [Num_FK_INST_NO], [Num_FK_CO_CD], [Num_FK_COPRT_NO])
    PRINT 'Created index: IX_TBL_STUDENT_INFO_PRN_NO'
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_INFO_INST_NO' AND object_id = OBJECT_ID('TBL_STUDENT_INFO'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_INFO_INST_NO] ON [dbo].[TBL_STUDENT_INFO] ([Num_FK_INST_NO])
    INCLUDE ([Num_PK_RECORD_ID], [Chr_PRN_NO], [Num_FK_CO_CD])
    PRINT 'Created index: IX_TBL_STUDENT_INFO_INST_NO'
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_INFO_CO_CD' AND object_id = OBJECT_ID('TBL_STUDENT_INFO'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_INFO_CO_CD] ON [dbo].[TBL_STUDENT_INFO] ([Num_FK_CO_CD])
    INCLUDE ([Num_PK_RECORD_ID], [Chr_PRN_NO], [Num_FK_INST_NO])
    PRINT 'Created index: IX_TBL_STUDENT_INFO_CO_CD'
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_INFO_COPRT_NO' AND object_id = OBJECT_ID('TBL_STUDENT_INFO'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_INFO_COPRT_NO] ON [dbo].[TBL_STUDENT_INFO] ([Num_FK_COPRT_NO])
    INCLUDE ([Num_PK_RECORD_ID], [Chr_PRN_NO])
    PRINT 'Created index: IX_TBL_STUDENT_INFO_COPRT_NO'
END
GO

-- TBL_STUDENT_EXAMS Indexes (Composite Primary Key)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_EXAMS_PRN_INST_COPRT' AND object_id = OBJECT_ID('TBL_STUDENT_EXAMS'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_EXAMS_PRN_INST_COPRT] ON [dbo].[TBL_STUDENT_EXAMS] 
    ([Chr_FK_PRN_NO], [Num_FK_INST_NO], [Num_FK_COPRT_NO])
    INCLUDE ([Num_ST_SEAT_NO], [Num_FK_CO_CD], [Chr_ST_COPRT_RES], [Chr_ST_YR_RES])
    PRINT 'Created index: IX_TBL_STUDENT_EXAMS_PRN_INST_COPRT'
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_EXAMS_INST_NO' AND object_id = OBJECT_ID('TBL_STUDENT_EXAMS'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_EXAMS_INST_NO] ON [dbo].[TBL_STUDENT_EXAMS] ([Num_FK_INST_NO])
    INCLUDE ([Chr_FK_PRN_NO], [Num_FK_COPRT_NO], [Chr_ST_COPRT_RES])
    PRINT 'Created index: IX_TBL_STUDENT_EXAMS_INST_NO'
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_EXAMS_CO_CD' AND object_id = OBJECT_ID('TBL_STUDENT_EXAMS'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_EXAMS_CO_CD] ON [dbo].[TBL_STUDENT_EXAMS] ([Num_FK_CO_CD])
    INCLUDE ([Chr_FK_PRN_NO], [Num_FK_INST_NO], [Num_FK_COPRT_NO])
    PRINT 'Created index: IX_TBL_STUDENT_EXAMS_CO_CD'
END
GO

-- TBL_STUDENT_SUBJECT Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_SUBJECT_PRN_NO' AND object_id = OBJECT_ID('TBL_STUDENT_SUBJECT'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_SUBJECT_PRN_NO] ON [dbo].[TBL_STUDENT_SUBJECT] ([Chr_FK_PRN_NO])
    INCLUDE ([Num_FK_INST_NO], [Num_FK_COPRT_NO], [NUM_FK_SUB_CD])
    PRINT 'Created index: IX_TBL_STUDENT_SUBJECT_PRN_NO'
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_SUBJECT_INST_COPRT' AND object_id = OBJECT_ID('TBL_STUDENT_SUBJECT'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_SUBJECT_INST_COPRT] ON [dbo].[TBL_STUDENT_SUBJECT] 
    ([Num_FK_INST_NO], [Num_FK_COPRT_NO])
    INCLUDE ([Chr_FK_PRN_NO], [NUM_FK_SUB_CD])
    PRINT 'Created index: IX_TBL_STUDENT_SUBJECT_INST_COPRT'
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_SUBJECT_SUB_CD' AND object_id = OBJECT_ID('TBL_STUDENT_SUBJECT'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_SUBJECT_SUB_CD] ON [dbo].[TBL_STUDENT_SUBJECT] ([NUM_FK_SUB_CD])
    INCLUDE ([Chr_FK_PRN_NO], [Num_FK_INST_NO], [Num_FK_COPRT_NO])
    PRINT 'Created index: IX_TBL_STUDENT_SUBJECT_SUB_CD'
END
GO

-- TBL_STUDENT_PAP_MARKS Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_PAP_MARKS_PRN_NO' AND object_id = OBJECT_ID('TBL_STUDENT_PAP_MARKS'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_PAP_MARKS_PRN_NO] ON [dbo].[TBL_STUDENT_PAP_MARKS] ([Chr_FK_PRN_NO])
    INCLUDE ([Num_FK_INST_NO], [Num_FK_COPRT_NO], [NUM_FK_SUB_CD], [NUM_FK_CAT_CD])
    PRINT 'Created index: IX_TBL_STUDENT_PAP_MARKS_PRN_NO'
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_PAP_MARKS_INST_COPRT' AND object_id = OBJECT_ID('TBL_STUDENT_PAP_MARKS'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_PAP_MARKS_INST_COPRT] ON [dbo].[TBL_STUDENT_PAP_MARKS] 
    ([Num_FK_INST_NO], [Num_FK_COPRT_NO])
    INCLUDE ([Chr_FK_PRN_NO], [NUM_FK_SUB_CD], [NUM_FK_CAT_CD])
    PRINT 'Created index: IX_TBL_STUDENT_PAP_MARKS_INST_COPRT'
END
GO

-- TBL_STUDENT_CAT_MARKS Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_CAT_MARKS_PRN_NO' AND object_id = OBJECT_ID('TBL_STUDENT_CAT_MARKS'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_CAT_MARKS_PRN_NO] ON [dbo].[TBL_STUDENT_CAT_MARKS] ([Chr_FK_PRN_NO])
    INCLUDE ([Num_FK_INST_NO], [Num_FK_COPRT_NO], [NUM_FK_SUB_CD], [NUM_FK_CAT_CD])
    PRINT 'Created index: IX_TBL_STUDENT_CAT_MARKS_PRN_NO'
END
GO

-- TBL_STUDENT_COURSE Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_COURSE_PRN_NO' AND object_id = OBJECT_ID('TBL_STUDENT_COURSE'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_COURSE_PRN_NO] ON [dbo].[TBL_STUDENT_COURSE] ([Chr_FK_PRN_NO])
    INCLUDE ([Num_FK_INST_NO], [Num_FK_CO_CD], [Num_FK_COPRT_NO])
    PRINT 'Created index: IX_TBL_STUDENT_COURSE_PRN_NO'
END
GO

-- TBL_STUDENT_CONVO Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_CONVO_PRN_NO' AND object_id = OBJECT_ID('TBL_STUDENT_CONVO'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_CONVO_PRN_NO] ON [dbo].[TBL_STUDENT_CONVO] ([Chr_FK_PRN_NO])
    INCLUDE ([Num_FK_INST_NO], [Num_FK_RESULT_CD])
    PRINT 'Created index: IX_TBL_STUDENT_CONVO_PRN_NO'
END
GO

-- TBL_STUDENT_CGPA Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_CGPA_PRN_NO' AND object_id = OBJECT_ID('TBL_STUDENT_CGPA'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_CGPA_PRN_NO] ON [dbo].[TBL_STUDENT_CGPA] ([Chr_FK_PRN_NO])
    INCLUDE ([Num_FK_INST_NO], [Num_FK_COPRT_NO])
    PRINT 'Created index: IX_TBL_STUDENT_CGPA_PRN_NO'
END
GO

-- TBl_STUDENT_ENV_STUDIES Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBl_STUDENT_ENV_STUDIES_PRN_NO' AND object_id = OBJECT_ID('TBl_STUDENT_ENV_STUDIES'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBl_STUDENT_ENV_STUDIES_PRN_NO] ON [dbo].[TBl_STUDENT_ENV_STUDIES] ([Chr_FK_PRN_NO])
    INCLUDE ([Num_FK_INST_NO])
    PRINT 'Created index: IX_TBl_STUDENT_ENV_STUDIES_PRN_NO'
END
GO

-- TBL_STUDENT_REVALUATION Indexes (Composite Key)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TBL_STUDENT_REVALUATION_PRN_INST_COPRT_SUB' AND object_id = OBJECT_ID('TBL_STUDENT_REVALUATION'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TBL_STUDENT_REVALUATION_PRN_INST_COPRT_SUB] ON [dbo].[TBL_STUDENT_REVALUATION] 
    ([NUM_FK_PRN_NO], [Num_FK_INST_NO], [Num_FK_COPRT_NO], [NUM_FK_SUB_CD])
    INCLUDE ([Chr_ST_REV_STATUS])
    PRINT 'Created index: IX_TBL_STUDENT_REVALUATION_PRN_INST_COPRT_SUB'
END
GO

-- =============================================
-- SECTION 2: COURSE MASTER TABLE INDEXES
-- =============================================

-- Tbl_COURSE_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_COURSE_MSTR_COURSE_CD' AND object_id = OBJECT_ID('Tbl_COURSE_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_COURSE_MSTR_COURSE_CD] ON [dbo].[Tbl_COURSE_MSTR] ([Num_PK_COURSE_CD])
    INCLUDE ([Chr_COURSE_NM])
    PRINT 'Created index: IX_Tbl_COURSE_MSTR_COURSE_CD'
END
GO

-- Tbl_COURSE_PART_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_COURSE_PART_MSTR_COURSE_COPRT' AND object_id = OBJECT_ID('Tbl_COURSE_PART_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_COURSE_PART_MSTR_COURSE_COPRT] ON [dbo].[Tbl_COURSE_PART_MSTR] 
    ([Num_FK_COURSE_CD], [Num_PK_COPRT_NO])
    INCLUDE ([Chr_COPRT_NM])
    PRINT 'Created index: IX_Tbl_COURSE_PART_MSTR_COURSE_COPRT'
END
GO

-- Tbl_COURSE_TYPE_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_COURSE_TYPE_MSTR_COURSE_TYPE_CD' AND object_id = OBJECT_ID('Tbl_COURSE_TYPE_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_COURSE_TYPE_MSTR_COURSE_TYPE_CD] ON [dbo].[Tbl_COURSE_TYPE_MSTR] ([Num_PK_COURSE_TYPE_CD])
    INCLUDE ([Chr_COURSE_TYPE_NM])
    PRINT 'Created index: IX_Tbl_COURSE_TYPE_MSTR_COURSE_TYPE_CD'
END
GO

-- =============================================
-- SECTION 3: COLLEGE MASTER TABLE INDEXES
-- =============================================

-- Tbl_COLLEGE_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_COLLEGE_MSTR_CO_CD' AND object_id = OBJECT_ID('Tbl_COLLEGE_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_COLLEGE_MSTR_CO_CD] ON [dbo].[Tbl_COLLEGE_MSTR] ([Num_PK_CO_CD])
    INCLUDE ([Chr_CO_NM])
    PRINT 'Created index: IX_Tbl_COLLEGE_MSTR_CO_CD'
END
GO

-- Tbl_COLLEGE_COURSE_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_COLLEGE_COURSE_MSTR_CO_COURSE' AND object_id = OBJECT_ID('Tbl_COLLEGE_COURSE_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_COLLEGE_COURSE_MSTR_CO_COURSE] ON [dbo].[Tbl_COLLEGE_COURSE_MSTR] 
    ([Num_FK_CO_CD], [Num_FK_COURSE_CD])
    INCLUDE ([Num_PK_RECORD_ID])
    PRINT 'Created index: IX_Tbl_COLLEGE_COURSE_MSTR_CO_COURSE'
END
GO

-- =============================================
-- SECTION 4: SUBJECT MASTER TABLE INDEXES
-- =============================================

-- Tbl_SUBJECT_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_SUBJECT_MSTR_SUB_CD' AND object_id = OBJECT_ID('Tbl_SUBJECT_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_SUBJECT_MSTR_SUB_CD] ON [dbo].[Tbl_SUBJECT_MSTR] ([Num_PK_SUB_CD])
    INCLUDE ([Chr_SUB_NM], [Chr_SUB_CODE])
    PRINT 'Created index: IX_Tbl_SUBJECT_MSTR_SUB_CD'
END
GO

-- Tbl_SUBJECT_CAT_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_SUBJECT_CAT_MSTR_SUB_CAT' AND object_id = OBJECT_ID('Tbl_SUBJECT_CAT_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_SUBJECT_CAT_MSTR_SUB_CAT] ON [dbo].[Tbl_SUBJECT_CAT_MSTR] 
    ([Num_FK_SUB_CD], [Num_PK_CAT_CD])
    INCLUDE ([Chr_CAT_NM])
    PRINT 'Created index: IX_Tbl_SUBJECT_CAT_MSTR_SUB_CAT'
END
GO

-- Tbl_SUB_CATPAP_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_SUB_CATPAP_MSTR_SUB_CAT_PAP' AND object_id = OBJECT_ID('Tbl_SUB_CATPAP_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_SUB_CATPAP_MSTR_SUB_CAT_PAP] ON [dbo].[Tbl_SUB_CATPAP_MSTR] 
    ([NUM_FK_SUB_CD], [NUM_FK_CAT_CD], [NUM_PK_PP_CD])
    INCLUDE ([Chr_PP_NM])
    PRINT 'Created index: IX_Tbl_SUB_CATPAP_MSTR_SUB_CAT_PAP'
END
GO

-- =============================================
-- SECTION 5: BRANCH MASTER TABLE INDEXES
-- =============================================

-- Tbl_BRANCH_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_BRANCH_MSTR_BR_CD' AND object_id = OBJECT_ID('Tbl_BRANCH_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_BRANCH_MSTR_BR_CD] ON [dbo].[Tbl_BRANCH_MSTR] ([Num_PK_BR_CD])
    INCLUDE ([Chr_BR_NM])
    PRINT 'Created index: IX_Tbl_BRANCH_MSTR_BR_CD'
END
GO

-- =============================================
-- SECTION 6: FACULTY MASTER TABLE INDEXES
-- =============================================

-- Tbl_FACULTY_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_FACULTY_MSTR_FACULTY_CD' AND object_id = OBJECT_ID('Tbl_FACULTY_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_FACULTY_MSTR_FACULTY_CD] ON [dbo].[Tbl_FACULTY_MSTR] ([Num_PK_FACULTY_CD])
    INCLUDE ([Chr_FACULTY_NM])
    PRINT 'Created index: IX_Tbl_FACULTY_MSTR_FACULTY_CD'
END
GO

-- =============================================
-- SECTION 7: INSTANCE/SYSTEM TABLE INDEXES
-- =============================================

-- Tbl_SYS_INST Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_SYS_INST_INST_NO' AND object_id = OBJECT_ID('Tbl_SYS_INST'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_SYS_INST_INST_NO] ON [dbo].[Tbl_SYS_INST] ([Num_PK_INST_NO])
    INCLUDE ([Chr_INST_NM])
    PRINT 'Created index: IX_Tbl_SYS_INST_INST_NO'
END
GO

-- =============================================
-- SECTION 8: FEE TABLE INDEXES
-- =============================================

-- Tbl_FEE_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_FEE_MSTR_FEE_CD' AND object_id = OBJECT_ID('Tbl_FEE_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_FEE_MSTR_FEE_CD] ON [dbo].[Tbl_FEE_MSTR] ([Num_PK_FEE_CD])
    INCLUDE ([Chr_FEE_NM])
    PRINT 'Created index: IX_Tbl_FEE_MSTR_FEE_CD'
END
GO

-- Tbl_FEE_DTL Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_FEE_DTL_FEE_CD' AND object_id = OBJECT_ID('Tbl_FEE_DTL'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_FEE_DTL_FEE_CD] ON [dbo].[Tbl_FEE_DTL] ([Num_FK_FEE_CD])
    INCLUDE ([Num_PK_RECORD_ID], [Num_FEE_AMT])
    PRINT 'Created index: IX_Tbl_FEE_DTL_FEE_CD'
END
GO

-- =============================================
-- SECTION 9: TIMETABLE TABLE INDEXES
-- =============================================

-- Tbl_TIMETABLE_TRX Indexes (Composite Key)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_TIMETABLE_TRX_INST_COPRT' AND object_id = OBJECT_ID('Tbl_TIMETABLE_TRX'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_TIMETABLE_TRX_INST_COPRT] ON [dbo].[Tbl_TIMETABLE_TRX] 
    ([Num_FK_INST_NO], [Num_FK_COPRT_NO], [Num_FK_Course_No])
    INCLUDE ([Num_FK_CO_CD], [NUM_FK_SUB_DIV_CD], [Dtm_DTE_CR])
    PRINT 'Created index: IX_Tbl_TIMETABLE_TRX_INST_COPRT'
END
GO

-- Tbl_TimeTableINST Indexes (Composite Key)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_TimeTableINST_INST_CO' AND object_id = OBJECT_ID('Tbl_TimeTableINST'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_TimeTableINST_INST_CO] ON [dbo].[Tbl_TimeTableINST] 
    ([Num_FK_INST_NO], [Num_PK_CO_CD])
    INCLUDE ([Chr_FreezeTimeTable])
    PRINT 'Created index: IX_Tbl_TimeTableINST_INST_CO'
END
GO

-- =============================================
-- SECTION 10: EXAM SCHEDULE TABLE INDEXES
-- =============================================

-- Tbl_EXAM_SCHEDULE_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_EXAM_SCHEDULE_MSTR_INST_NO' AND object_id = OBJECT_ID('Tbl_EXAM_SCHEDULE_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_EXAM_SCHEDULE_MSTR_INST_NO] ON [dbo].[Tbl_EXAM_SCHEDULE_MSTR] ([Num_FK_INST_NO])
    INCLUDE ([Num_PK_EXAM_SCHEDULE_CD], [Chr_EXAM_SCHEDULE_NM])
    PRINT 'Created index: IX_Tbl_EXAM_SCHEDULE_MSTR_INST_NO'
END
GO

-- =============================================
-- SECTION 11: REGISTRATION TEMP TABLE INDEXES
-- =============================================

-- Tbl_REG_TEMP Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_REG_TEMP_PRN_NO' AND object_id = OBJECT_ID('Tbl_REG_TEMP'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_REG_TEMP_PRN_NO] ON [dbo].[Tbl_REG_TEMP] ([Chr_FK_PRN_NO])
    INCLUDE ([Num_PK_RECORD_ID], [Num_FK_INST_NO], [Dtm_DTE_CR])
    PRINT 'Created index: IX_Tbl_REG_TEMP_PRN_NO'
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_REG_TEMP_INST_NO' AND object_id = OBJECT_ID('Tbl_REG_TEMP'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_REG_TEMP_INST_NO] ON [dbo].[Tbl_REG_TEMP] ([Num_FK_INST_NO])
    INCLUDE ([Num_PK_RECORD_ID], [Chr_FK_PRN_NO], [Dtm_DTE_CR])
    PRINT 'Created index: IX_Tbl_REG_TEMP_INST_NO'
END
GO

-- Tbl_APP_TEMP Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_APP_TEMP_PRN_NO' AND object_id = OBJECT_ID('Tbl_APP_TEMP'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_APP_TEMP_PRN_NO] ON [dbo].[Tbl_APP_TEMP] ([Chr_FK_PRN_NO])
    INCLUDE ([Num_PK_RECORD_ID], [Num_FK_INST_NO])
    PRINT 'Created index: IX_Tbl_APP_TEMP_PRN_NO'
END
GO

-- Tbl_APP_TEMP_SUB Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_APP_TEMP_SUB_RECORD_ID' AND object_id = OBJECT_ID('Tbl_APP_TEMP_SUB'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_APP_TEMP_SUB_RECORD_ID] ON [dbo].[Tbl_APP_TEMP_SUB] ([Num_FK_RECORD_ID])
    INCLUDE ([NUM_FK_SUB_CD])
    PRINT 'Created index: IX_Tbl_APP_TEMP_SUB_RECORD_ID'
END
GO

-- =============================================
-- SECTION 12: CONVOCATION TABLE INDEXES
-- =============================================

-- Tbl_CONVO_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_CONVO_MSTR_CONVO_CD' AND object_id = OBJECT_ID('Tbl_CONVO_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_CONVO_MSTR_CONVO_CD] ON [dbo].[Tbl_CONVO_MSTR] ([Num_PK_CONVO_CD])
    INCLUDE ([Chr_CONVO_NM])
    PRINT 'Created index: IX_Tbl_CONVO_MSTR_CONVO_CD'
END
GO

-- =============================================
-- SECTION 13: GRADE TABLE INDEXES
-- =============================================

-- Tbl_GRADE_MSTR Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_GRADE_MSTR_GRADE_CD' AND object_id = OBJECT_ID('Tbl_GRADE_MSTR'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_GRADE_MSTR_GRADE_CD] ON [dbo].[Tbl_GRADE_MSTR] ([Num_PK_GRADE_CD])
    INCLUDE ([Chr_GRADE_NM])
    PRINT 'Created index: IX_Tbl_GRADE_MSTR_GRADE_CD'
END
GO

-- =============================================
-- SECTION 14: MARKS TEMP TABLE INDEXES
-- =============================================

-- Tbl_MARKS_TMP Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Tbl_MARKS_TMP_RECORDID' AND object_id = OBJECT_ID('Tbl_MARKS_TMP'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_Tbl_MARKS_TMP_RECORDID] ON [dbo].[Tbl_MARKS_TMP] ([Num_PK_RECORDID])
    INCLUDE ([Chr_FK_PRN_NO], [Num_FK_INST_NO])
    PRINT 'Created index: IX_Tbl_MARKS_TMP_RECORDID'
END
GO

PRINT 'Index optimization completed for BHVEDPSNET database!'
GO






